---
- name: Configure apache server
  hosts: webserver
  remote_user: ansible
  become: yes
  ignore_errors: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Create content
      copy:
        src: /home/ansible/teste.html
        dest: /var/www/html/index.html
    - name: allow firewall for http
      firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes
      ignore_errors: yes
    - name: allow firewall for https
      firewalld:
        service: https
        state: enabled
        immediate: yes
        permanent: yes
      ignore_errors: yes
    - name: start and enable http
      service:
        name: httpd
        state: started
        enabled: yes
